# Generated by Django 4.2.13 on 2024-06-26 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoLiveStreaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
