version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoLiveStreaming.settings

  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 DjangoLiveStreaming.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
